# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Lab07' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lab07
  pod 'Firebase/Core'  
  pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'

  target 'Lab07Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Lab07UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
